### ISSUE TITLE
[IE] brackets-paste-and-indent throws in IE, fails to load

### ISSUE THREAD

**Issue by humphd** [humphd/brackets#285]
```
[Extension] failed to load /src/extensions/default/brackets-paste-and-indent - TypeError: Unable to get property 'split' of undefined or null reference
TypeError: Unable to get property 'split' of undefined or null reference
   at deprecationWarning (http://192.168.2.117:8080/src/utils/DeprecationWarning.js:85:13)
   at jQuery.fn.init (http://192.168.2.117:8080/src/brackets.js:460:17)
   at n (http://192.168.2.117:8080/src/thirdparty/jquery-2.1.3.min.js:2:398)
   at Anonymous function (http://192.168.2.117:8080/src/extensions/default/brackets-paste-and-indent/main.js:28:5)
   at context.execCb (http://192.168.2.117:8080/src/thirdparty/requirejs/require.js:1658:17)
   at Module.prototype.check (http://192.168.2.117:8080/src/thirdparty/requirejs/require.js:869:37)
   at Module.prototype.enable (http://192.168.2.117:8080/src/thirdparty/requirejs/require.js:1151:17)
   at Module.prototype.init (http://192.168.2.117:8080/src/thirdparty/requirejs/require.js:782:21)
   at callGetModule (http://192.168.2.117:8080/src/thirdparty/requirejs/require.js:1178:17)
   at context.completeLoad (http://192.168.2.117:8080/src/thirdparty/requirejs/require.js:1552:21)
```

**Comment by humphd** [comment]
This is a bug upstream, for which I've done a PR: https://github.com/adobe/brackets/pull/11124

**Comment by humphd** [comment]
@gideonthomas I suspect I'm not going to get a fast reply to this upstream fix.  Can you please review it, and we can take it here in the meantime.

**Comment by gideonthomas** [comment]
@humphd sure, do you want to do a pr here?

**Comment by gideonthomas** [comment]
nvm r+ for the PR adobe#11124

**Comment by humphd** [comment]
I've landed this in bramble locally, I'm going to close here.

**Comment by abose** [comment]
@humphd I have merged the PR in brackets. Thanks :)
